services:
  - type: web
    name: kodjo-english-app
    env: node
    nodeVersion: 18.18.0
    buildCommand: npm run render:build
    startCommand: npm run render:start
    envVars:
      - key: NODE_ENV
        value: production
      - key: VITE_API_URL
        value: /api
      - key: VITE_DISABLE_CHARTS_SSR
        value: "true"
      - key: DATABASE_TYPE
        value: sqlite
      - key: DATABASE_PATH
        value: ./data/kodjo-english-v2.db
      - key: TELEGRAM_BOT_TOKEN
        sync: false
      - key: ZOOM_CLIENT_ID
        sync: false
      - key: ZOOM_CLIENT_SECRET
        sync: false
      - key: ZOOM_ACCOUNT_ID
        sync: false
      - key: SESSION_SECRET
        generateValue: true
      - key: DATABASE_TYPE
        value: sqlite
      - key: DATABASE_PATH
        value: ./data/kodjo-english-v2.db
    disk:
      name: data
      mountPath: /opt/render/project/src/data
      sizeGB: 1
