services:
  - type: web
    name: kodjo-english-app
    env: node
    nodeVersion: 18.18.0
    buildCommand: chmod +x render-build.sh && ./render-build.sh
    startCommand: chmod +x render-start.sh && ./render-start.sh
    envVars:
      - key: NODE_ENV
        value: production
      - key: VITE_API_URL
        value: /api
      - key: VITE_DISABLE_CHARTS_SSR
        value: "true"
      - key: TELEGRAM_BOT_TOKEN
        sync: false
      - key: ZOOM_CLIENT_ID
        sync: false
      - key: ZOOM_CLIENT_SECRET
        sync: false
      - key: ZOOM_ACCOUNT_ID
        sync: false
      - key: SESSION_SECRET
        generateValue: true
      - key: DATABASE_TYPE
        value: sqlite
      - key: DATABASE_PATH
        value: ./data/kodjo-english-v2.db
    disk:
      name: data
      mountPath: /opt/render/project/src/data
      sizeGB: 1
